### PR TITLE
Bring up to date with some md5-file features

### PR DESCRIPTION
**Pull request by aidandj**

### CODE REVIEW

**Comment by aidandj** [comment]
@LinusU I copied this over from md5-file package.

**Comment by aidandj** [comment]
@LinusU is there anything else this needs?

**Comment by aidandj** [comment]
@LinusU pinging again

**Comment by LinusU** [comment]
Sorry for the delay!

For future reference, please don't bump the version number in the PR as we want a tagged commit that specifically bumps it.

**Review by LinusU — APPROVED** [review]

**Comment by LinusU** [comment]
Released as [🚢 0.3.0 / 2021-10-18](https://github.com/LinusU/md5-dir/releases/tag/v0.3.0)

**Comment by aidandj** [comment]
Thanks!

**Pull request merged**
